import express, { Router } from 'express';
import { getAdminDashboardStats, getAdminDeliveryAnalytics, getAdminRecentActivities, getAdminGlobalSearch } from '../controllers/adminDashboardController.js';
import { getAdminOngoingDeliveries, getAdminOrdersByStatus, getAdminOrderById, getAdminOrderQRScans, createAdminOrder, cancelAdminOrder } from '../controllers/adminOrderController.js';
import { getAdminFinancialStats, getAdminTransactions, getAdminReportDeliveries, getAdminReportRevenues, getAdminReportClients, getAdminReportDrivers, getAdminReportPayments } from '../controllers/adminFinanceController.js';
import { getAdminDriverDetails, updateAdminDriverStatus, getAdminDrivers, getAdminDriverFullDetails, rechargeAdminDriverCommission, suspendAdminDriverCommission, updateAdminDriverCommissionRate, getAdminDriverCommissionTransactions } from '../controllers/adminDriverController.js';
import { getAdminUsers, getAdminClientDetails, getAdminClientStatistics, getAdminAdminDetails, updateStaffRole } from '../controllers/adminUserController.js';
import { getAdminRatings, deleteAdminRating, getAdminPromoCodes, createAdminPromoCode, getAdminDisputes, updateAdminDispute } from '../controllers/adminModerationController.js';
import { createConversation, getConversationById, getConversations, getMessages, getUnreadCount, markMessagesAsRead, sendMessage } from '../controllers/messageController.js';
import { verifyAdminSupabase } from '../middleware/verifyAdminSupabase.js';
import { requireSuperAdmin } from '../middleware/requireSuperAdmin.js';

const router: Router = express.Router();


router.get('/dashboard-stats', verifyAdminSupabase, getAdminDashboardStats);
router.get('/delivery-analytics', verifyAdminSupabase, getAdminDeliveryAnalytics);
router.get('/recent-activities', verifyAdminSupabase, getAdminRecentActivities);
router.get('/ongoing-deliveries', verifyAdminSupabase, getAdminOngoingDeliveries);
router.get('/orders', verifyAdminSupabase, getAdminOrdersByStatus);
router.get('/orders/:orderId/qr-scans', verifyAdminSupabase, getAdminOrderQRScans);
router.get('/orders/:orderId', verifyAdminSupabase, getAdminOrderById);
router.post('/orders', verifyAdminSupabase, createAdminOrder);
router.post('/orders/:orderId/cancel', verifyAdminSupabase, cancelAdminOrder);
router.get('/users', verifyAdminSupabase, getAdminUsers);
router.get('/search', verifyAdminSupabase, getAdminGlobalSearch);
router.get('/financial-stats', verifyAdminSupabase, requireSuperAdmin, getAdminFinancialStats);
router.get('/transactions', verifyAdminSupabase, requireSuperAdmin, getAdminTransactions);
router.get('/reports/deliveries', verifyAdminSupabase, requireSuperAdmin, getAdminReportDeliveries);
router.get('/reports/revenues', verifyAdminSupabase, requireSuperAdmin, getAdminReportRevenues);
router.get('/reports/clients', verifyAdminSupabase, requireSuperAdmin, getAdminReportClients);
router.get('/reports/drivers', verifyAdminSupabase, requireSuperAdmin, getAdminReportDrivers);
router.get('/reports/payments', verifyAdminSupabase, requireSuperAdmin, getAdminReportPayments);
router.get('/drivers', verifyAdminSupabase, getAdminDrivers);
router.get('/drivers/:driverId', verifyAdminSupabase, getAdminDriverFullDetails);
router.get('/drivers/:driverId/details', verifyAdminSupabase, getAdminDriverDetails);
router.put('/drivers/:driverId/status', verifyAdminSupabase, updateAdminDriverStatus);
router.post('/drivers/:driverId/commission/recharge', verifyAdminSupabase, requireSuperAdmin, rechargeAdminDriverCommission);
router.put('/drivers/:driverId/commission/suspend', verifyAdminSupabase, suspendAdminDriverCommission);
router.put('/drivers/:driverId/commission/rate', verifyAdminSupabase, updateAdminDriverCommissionRate);
router.get('/drivers/:driverId/commission/transactions', verifyAdminSupabase, getAdminDriverCommissionTransactions);
router.get('/clients/:clientId/details', verifyAdminSupabase, getAdminClientDetails);
router.get('/clients/:clientId/statistics', verifyAdminSupabase, getAdminClientStatistics);
router.get('/admins/:adminId/details', verifyAdminSupabase, getAdminAdminDetails);
router.put('/users/:userId/role', verifyAdminSupabase, requireSuperAdmin, updateStaffRole);
router.get('/ratings', verifyAdminSupabase, getAdminRatings);
router.delete('/ratings/:ratingId', verifyAdminSupabase, deleteAdminRating);
router.get('/promo-codes', verifyAdminSupabase, getAdminPromoCodes);
router.post('/promo-codes', verifyAdminSupabase, createAdminPromoCode);
router.get('/disputes', verifyAdminSupabase, getAdminDisputes);
router.put('/disputes/:disputeId', verifyAdminSupabase, updateAdminDispute);
router.get('/messages/conversations', verifyAdminSupabase, getConversations);
router.get('/messages/conversations/:conversationId', verifyAdminSupabase, getConversationById);
router.post('/messages/conversations', verifyAdminSupabase, createConversation);
router.get('/messages/conversations/:conversationId/messages', verifyAdminSupabase, getMessages);
router.post('/messages/conversations/:conversationId/messages', verifyAdminSupabase, sendMessage);
router.put('/messages/conversations/:conversationId/read', verifyAdminSupabase, markMessagesAsRead);
router.get('/messages/unread-count', verifyAdminSupabase, getUnreadCount);

export default router;

